repos:
  -   repo: https://github.com/Yelp/detect-secrets.git
      rev: v1.3.0
      hooks:
      -   id: detect-secrets
          args: ['--baseline', '.secrets.baseline']
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
      -   id: end-of-file-fixer
